server:
  port: 8081
  servlet:
    context-path: /api
spring:
  application:
    name: PizzaProject
  datasource:
    password: admin
    url: jdbc:mysql://localhost:3306/payment_service
    username: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
payment-service:
  rabbitmq:
    queue: pizza-project.queue
pizza-project:
  baseUrl: http://localhost:8080/api/productOrders